### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by michaelscl** [starcraft66/docker-kerio-connect#1]
Hi,

Are you sure with:
`VOLUME /opt/kerio/mailserver/cluster.cfg /opt/kerio/mailserver/users.cfg /opt/kerio/mailserver/mailserver.cfg /opt/kerio/mailserver/stats.dat /opt/kerio/mailserver/license /opt/kerio/mailserver/store /opt/kerio/mailserver/sslcert /opt/kerio/mailserver/stats.dat /opt/kerio/mailserver/charts.dat`
? 
It creates **directories**, not files!

VOLUME is only for directories...... or?

mt

**Comment by starcraft66** [comment]
Hello, you are correct that this creates folders inside the container. I wrote this Dockerfile a long time ago and didn't realize this. I think it would be cleaner to just make `/opt/kerio/mailserver` a volume instead, I can fix this in a later release. However, the docker `-v` option allows you to mount files as well as folders so if you mount a file with docker `-v` or via `docker-compose`, it will override the folder created inside the container.

Edit: To clarify, if using `-v` or `docker-compose`, make sure the files exist on disk (copy an existing kerio install or make empty ones) before running the command or else docker will create folders by default.

**Comment by michaelscl** [comment]
Yes, I understand. It is a little bit complicated for the clean install.....

**Comment by starcraft66** [comment]
Sorry for the confusion, I will do more testing with a clean install and update the instructions accordingly.
